### ISSUE TITLE
Mix channels for a specific bus

### ISSUE THREAD

**Issue by briceparent** [onyx-and-iris/xair-api-python#4]
Hi! Great work mate!

I have a MR18, and I'd like to use this to update the mix for a bus, give each channel a specific volume value and mute state, but only on a specific output bus. The purpose is to have different mixes depending on which song we're playing.
I can't try it out right now, as the MR18 is physically in a friend's house where we play music together, but I'd like to write a few test lines of code before going there, so that I don't have to explore and start fresh during the time we're supposed to play.

I would do things like this pseudo code:

def set_song_1():
    mr18.bus[2].channels[7].volume = 0.7
    mr18.bus[2].channels[8].mute = True

Is my use case possible with this tool?

Thanks a lot!
Brice

**Comment by onyx-and-iris** [comment]
Hi, any OSC command defined in the [XAir Documentation](https://behringer.world/wiki/doku.php?id=x-air_osc) can be sent to the mixer with the [base class send method](https://github.com/onyx-and-iris/xair-api-python#xairremote-class-lower-level) even if no class or method is defined for that command.

I think to adjust the level for a channel for a mixbus you'd want to adjust the channel send for that mixbus. So these commands: `/ch/01/mix/01/level`. Unfortunately, due to how I implemented the mix class it's currently not possible to access these OSC addresses through the interface. I'll need to investigate it.

I don't think individual channels have mute states per mixbus on the xair series, right? If I remember correctly, mute states were tied to the main LR. So you might need to just adjust the send level to -90 (-inf in XAIR Edit).

I hope that's helpful.

**Comment by briceparent** [comment]
Thanks a lot, it is really helpful!
I believe you're right about the mute states. And about how it does not really matter as I can always set their level to 0.
I'll try directly with the base class send feature then, it will be plenty enough for my use case.
Thanks again!

**Comment by florczakraf** [comment]
> I don't think individual channels have mute states per mixbus on the xair series, right? If I remember correctly, mute states were tied to the main LR. So you might need to just adjust the send level to 0.

Yeah, mute state is global, not only tied to the main but all outs.

**Comment by onyx-and-iris** [comment]
I'll close this issue for now but I make a note to investigate channel sends for mixbuses.
